import { Country } from './country.model';

export const COUNTRIES: Country[] = [
  { name: 'السعودية', code: 'sa', dialCode: '+966' },
  { name: 'مصر', code: 'eg', dialCode: '+20' },
  { name: 'الإمارات', code: 'ae', dialCode: '+971' },
  { name: 'الكويت', code: 'kw', dialCode: '+965' },
  { name: 'قطر', code: 'qa', dialCode: '+974' },
  { name: 'البحرين', code: 'bh', dialCode: '+973' },
  { name: 'عُمان', code: 'om', dialCode: '+968' },
  { name: 'الأردن', code: 'jo', dialCode: '+962' },
  { name: 'لبنان', code: 'lb', dialCode: '+961' },
  { name: 'سوريا', code: 'sy', dialCode: '+963' },
  { name: 'العراق', code: 'iq', dialCode: '+964' },
  { name: 'اليمن', code: 'ye', dialCode: '+967' },
  { name: 'المغرب', code: 'ma', dialCode: '+212' },
  { name: 'الجزائر', code: 'dz', dialCode: '+213' },
  { name: 'تونس', code: 'tn', dialCode: '+216' },
  { name: 'ليبيا', code: 'ly', dialCode: '+218' },
  { name: 'السودان', code: 'sd', dialCode: '+249' },
  { name: 'الولايات المتحدة', code: 'us', dialCode: '+1' },
  { name: 'المملكة المتحدة', code: 'gb', dialCode: '+44' },
  { name: 'كندا', code: 'ca', dialCode: '+1' },
  { name: 'أستراليا', code: 'au', dialCode: '+61' },
  { name: 'فرنسا', code: 'fr', dialCode: '+33' },
  { name: 'ألمانيا', code: 'de', dialCode: '+49' },
  { name: 'إيطاليا', code: 'it', dialCode: '+39' },
  { name: 'إسبانيا', code: 'es', dialCode: '+34' },
  { name: 'الهند', code: 'in', dialCode: '+91' },
  { name: 'الصين', code: 'cn', dialCode: '+86' },
  { name: 'اليابان', code: 'jp', dialCode: '+81' },
  { name: 'كوريا الجنوبية', code: 'kr', dialCode: '+82' },
  { name: 'روسيا', code: 'ru', dialCode: '+7' },
  { name: 'تركيا', code: 'tr', dialCode: '+90' },
  { name: 'إيران', code: 'ir', dialCode: '+98' },
  { name: 'باكستان', code: 'pk', dialCode: '+92' },
  { name: 'بنغلاديش', code: 'bd', dialCode: '+880' },
  { name: 'إندونيسيا', code: 'id', dialCode: '+62' },
  { name: 'ماليزيا', code: 'my', dialCode: '+60' },
  { name: 'سنغافورة', code: 'sg', dialCode: '+65' },
  { name: 'تايلاند', code: 'th', dialCode: '+66' },
  { name: 'الفلبين', code: 'ph', dialCode: '+63' },
  { name: 'فيتنام', code: 'vn', dialCode: '+84' },
  { name: 'جنوب أفريقيا', code: 'za', dialCode: '+27' },
  { name: 'نيجيريا', code: 'ng', dialCode: '+234' },
  { name: 'كينيا', code: 'ke', dialCode: '+254' },
  { name: 'البرازيل', code: 'br', dialCode: '+55' },
  { name: 'الأرجنتين', code: 'ar', dialCode: '+54' },
  { name: 'المكسيك', code: 'mx', dialCode: '+52' },
  { name: 'تشيلي', code: 'cl', dialCode: '+56' },
  { name: 'كولومبيا', code: 'co', dialCode: '+57' },
];

